import { useState } from "react";
import { BookingConversation } from "./BookingConversation";

export function Agent4Panel({
  followups,
  bookings,
  bookingMessages,
  onMarkFollowupSent,
  onMarkBookingSent,
}: {
  followups: Array<{ id: string; venue_name?: string; followup_number?: number; subject?: string }>;
  bookings: Array<{ id: string; venue_name: string; conversation_stage: string }>;
  bookingMessages: Record<string, Array<{ id: string; stage: string; subject: string; body: string; status: string }>>;
  onMarkFollowupSent: (id: string) => Promise<void>;
  onMarkBookingSent: (id: string) => Promise<void>;
}) {
  const [tab, setTab] = useState<"followups" | "bookings" | "seasonal">("followups");
  const [selectedBooking, setSelectedBooking] = useState<string | null>(null);
  return (
    <div className="space-y-3">
      <div className="flex gap-2">
        <button className="rounded bg-slate-700 px-2 py-1 text-xs text-white" onClick={() => setTab("followups")}>Follow-Ups</button>
        <button className="rounded bg-slate-700 px-2 py-1 text-xs text-white" onClick={() => setTab("bookings")}>Active Bookings</button>
        <button className="rounded bg-slate-700 px-2 py-1 text-xs text-white" onClick={() => setTab("seasonal")}>Seasonal</button>
      </div>
      {tab === "followups" ? (
        <div className="space-y-2">
          {followups.map((f) => (
            <div key={f.id} className="rounded border border-slate-700 bg-slate-900 p-3">
              <div className="text-sm text-white">{f.venue_name || "Venue"} · Follow-up #{f.followup_number}</div>
              <div className="text-xs text-slate-300">{f.subject}</div>
              <button onClick={() => onMarkFollowupSent(f.id)} className="mt-2 rounded bg-emerald-600 px-2 py-1 text-xs text-white">Mark Sent</button>
            </div>
          ))}
        </div>
      ) : null}
      {tab === "bookings" ? (
        <div className="grid gap-3 md:grid-cols-2">
          <div className="space-y-2">
            {bookings.map((b) => (
              <button key={b.id} onClick={() => setSelectedBooking(b.id)} className="w-full rounded border border-slate-700 bg-slate-900 p-3 text-left">
                <div className="text-white">{b.venue_name}</div>
                <div className="text-xs text-slate-400">{b.conversation_stage}</div>
              </button>
            ))}
          </div>
          <BookingConversation messages={bookingMessages[selectedBooking || ""] || []} onMarkSent={onMarkBookingSent} />
        </div>
      ) : null}
      {tab === "seasonal" ? <div className="rounded border border-slate-700 bg-slate-900 p-3 text-sm text-slate-300">Seasonal re-engagement drafts are generated by Agent 4 in the outreach queue.</div> : null}
    </div>
  );
}
